import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { CategoryScreen, Loader, Navbar } from '@/components';
import videoStore from '@/store/videoStore';
import { VideoCard } from './Home/components';
import { Suspense } from 'react';

export default function Home() {
  const videos = videoStore((state) => state.videos);
  const loading = videoStore((state) => state.loading);

  return (
    <Suspense fallback={<Loader />}>
      <Head>
        <title>Home - UMUSIC</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <meta name='robots' content='index, follow' />
        <meta httpEquiv='X-UA-Compatible' content='IE=edge' />
        <meta charset='utf-8' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <CategoryScreen />
      {loading && <Loader />}
      <main className={styles.homeContainer}>
        {videos?.map((video) => (
          <VideoCard key={video?.video?.videoId} video={video.video} />
        ))}
      </main>
    </Suspense>
  );
}
